import bcrypt from 'bcryptjs';

const data = {
    users: [
        {
            name: 'Suprith',
            email: 'admin@example.com',
            password: bcrypt.hashSync('1234', 8),
            isAdmin: true,
        },
        {
            name: 'John',
            email: 'user@example.com',
            password: bcrypt.hashSync('1234', 8),
            isAdmin: false,
        },
    ],
    products: [
        {
            name: 'IDLY',
            category: 'Breakfast',
            image: '/images/p1.jpg',
            price: 12,
            countInStock: 10,
            brand: 'Batter',
            rating: 4.5,
            numReviews: 10,
            description: 'Healthiest food of India',
        },
        {
            name: 'DOSA',
            category: 'Breakfast',
            image: '/images/p2.jpg',
            price: 10,
            countInStock: 20,
            brand: 'Batter',
            rating: 4.0,
            numReviews: 10,
            description: 'The essence of South India',
        },
        {
            name: 'SET DOSA',
            category: 'Breakfast',
            image: '/images/p3.jpg',
            price: 12,
            countInStock: 0,
            brand: 'Inhouse',
            rating: 4.8,
            numReviews: 17,
            description: 'Indian PanCake served with coconut chutney and sambhar ',
        },
        {
            name: 'MEDU VADA',
            category: 'Breakfast',
            image: '/images/p4.jpg',
            price: 8,
            countInStock: 15,
            brand: 'Batter',
            rating: 4.5,
            numReviews: 14,
            description: 'The Superb Delicacy of Karnataka from the ages',
        },
        {
            name: 'Parota',
            category: 'Lunch',
            image: '/images/p5.jpg',
            price: 15,
            countInStock: 5,
            brand: 'Coles Potato',
            rating: 4.5,
            numReviews: 10,
            description: 'Common Breakfast Lunch and Dinner of North India',
        },
        {
            name: 'Pani Puri',
            category: 'Snacks',
            image: '/images/p6.jpg',
            price: 13,
            countInStock: 12,
            brand: 'Tamarind',
            rating: 4.5,
            numReviews: 15,
            description: 'Tangy Water and Tangy sauce with some fat puri, The heart of Indian food system ',
        },
    ],
};
export default data;